// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// Cpp_rowSums
NumericVector Cpp_rowSums(const NumericMatrix& x);
RcppExport SEXP _gamstackr_Cpp_rowSums(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(Cpp_rowSums(x));
    return rcpp_result_gen;
END_RCPP
}
// get_derivs_cpp
List get_derivs_cpp(arma::mat& eta, arma::vec& theta, int deriv, int n_k, int dim_num, arma::mat& x, arma::mat& dens_matrix, List store);
RcppExport SEXP _gamstackr_get_derivs_cpp(SEXP etaSEXP, SEXP thetaSEXP, SEXP derivSEXP, SEXP n_kSEXP, SEXP dim_numSEXP, SEXP xSEXP, SEXP dens_matrixSEXP, SEXP storeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type deriv(derivSEXP);
    Rcpp::traits::input_parameter< int >::type n_k(n_kSEXP);
    Rcpp::traits::input_parameter< int >::type dim_num(dim_numSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type dens_matrix(dens_matrixSEXP);
    Rcpp::traits::input_parameter< List >::type store(storeSEXP);
    rcpp_result_gen = Rcpp::wrap(get_derivs_cpp(eta, theta, deriv, n_k, dim_num, x, dens_matrix, store));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_gamstackr_Cpp_rowSums", (DL_FUNC) &_gamstackr_Cpp_rowSums, 1},
    {"_gamstackr_get_derivs_cpp", (DL_FUNC) &_gamstackr_get_derivs_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_gamstackr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
